// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Yami_SkipTitle","status":false,"description":"Skip the title scene for testing purpose.","parameters":{}},
{"name":"GALV_MessageBusts","status":false,"description":"(v.2.6) Displays a bust image instead of selected face image","parameters":{"Bust Priority":"0","Bust Position":"0","Text X Offset":"390","Filename Append":""}},
{"name":"GALV_MessageSoundEffects","status":true,"description":"Play sound effects when during Show Text event commands.","parameters":{"Delay Time":"4","Default Talk SE":"Cursor1,65,100","Default Confirm SE":"","-----------":"","Quick SE 1":"","Quick SE 2":"","Quick SE 3":"","Quick SE 4":""}},
{"name":"Galv_NewItemIndication","status":true,"description":"(v.1.0) Adds a 'new' icon over items that have been obtained for the first time","parameters":{"New Icon Image":"newIcon","Icon X Offset":"0","Icon Y Offset":"0"}},
{"name":"GALV_CharacterFrames","status":true,"description":"Enables map character sheets to have more frames per character.","parameters":{"Frame Speed Modifier":"f * 0.8"}},
{"name":"GALV_CFStepSE","status":true,"description":"Adds step sound effects to Galv's Character Frames plugin","parameters":{"Step Frames":"1,5","Events":"true","-- Terrain Step SE --":"","Terrain 1":"Crossbow,10,130","Terrain 2":"","Terrain 3":"","Terrain 4":"","Terrain 5":"","Terrain 6":"","Terrain 7":""}},
{"name":"GainItemUpdate","status":true,"description":"Popup a window to display what item you get from the event","parameters":{"Offset X":"0","Offset Y":"0"}},
{"name":"KMS_SaveWithSnap","status":true,"description":"[v0.1.0] Add captured image on save/load scene.","parameters":{"Image scale":"0.15","Enable JPEG":"1"}},
{"name":"AXY_TitleMenu","status":true,"description":"v1.00 Display Multiple Menu in Title Screen.","parameters":{"DisplayJumpToMap":"false","JumpToMapText":"JumpToMap","JumpToMapId":"1","JumpToMapSwitchId":"0","DisplayExit":"true","ExitText":"结束游戏","MaxCols":"1","WindowWidth":"240","X":"(Graphics.boxWidth - this.width) / 2","Y":"Graphics.boxHeight - this.height - 150","WindowSkin":"Window","Align":"center","TextColor":"#FFFFFF"}}
];
